from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .models import GroundedConfig, Spec
from .registry import SpecRegistry
from .rich_text import rich_text_plain


GENERATED_BLOCK_PREFIX = "grounded:generated"


@dataclass(frozen=True)
class GeneratedDocument:
    spec: Spec
    path: Path
    content: str
    write_mode: str


def generated_documents(
    config: GroundedConfig, registry: SpecRegistry
) -> list[GeneratedDocument]:
    documents: list[GeneratedDocument] = []
    for spec in sorted(
        registry.active_specs,
        key=lambda item: (item.data.get("output_path", ""), item.id),
    ):
        if spec.kind != "generated_document":
            continue
        output_path = spec.data.get("output_path")
        if not isinstance(output_path, str) or not output_path:
            continue
        if spec.data.get("format") != "markdown":
            continue
        path = config.root / output_path
        documents.append(
            GeneratedDocument(
                spec=spec,
                path=path,
                content=render_generated_document(spec, registry),
                write_mode=_write_mode(spec),
            )
        )
    return documents


def render_generated_document(document: Spec, registry: SpecRegistry) -> str:
    lines: list[str] = []
    front_matter = document.data.get("front_matter")
    if isinstance(front_matter, dict) and front_matter:
        lines.append("---")
        for key, value in sorted(front_matter.items()):
            if isinstance(key, str) and isinstance(value, str):
                lines.append(f"{key}: {value}")
        lines.extend(["---", ""])

    title = document.data.get("title")
    if isinstance(title, str) and title:
        lines.extend([f"# {title}", ""])

    lines.extend(
        [
            "<!-- This document is generated by Grounded. Edit the source specs, not this prose. -->",
            f"<!-- owner: {document.id} -->",
        ]
    )
    purpose = document.data.get("purpose")
    if isinstance(purpose, str) and purpose:
        lines.extend(["", purpose])

    section_refs = _string_list(document.data.get("section_refs"))
    sections = [
        section
        for section_id in section_refs
        if (section := registry.get(section_id)) is not None
        and section.kind == "document_section"
    ]
    sections.sort(key=lambda item: (_integer_value(item.data.get("order")), item.id))
    for section in sections:
        lines.extend(["", *_render_section(section, registry)])
    return "\n".join(lines).rstrip() + "\n"


def _write_mode(document: Spec) -> str:
    value = document.data.get("write_mode")
    if value in {"protected_block", "full_file"}:
        return value
    return "protected_block"


def block_start(document_id: str) -> str:
    return f"<!-- {GENERATED_BLOCK_PREFIX}:start {document_id} -->"


def block_end(document_id: str) -> str:
    return f"<!-- {GENERATED_BLOCK_PREFIX}:end {document_id} -->"


def protected_block(document_id: str, content: str) -> str:
    return f"{block_start(document_id)}\n{content.rstrip()}\n{block_end(document_id)}\n"


def replace_protected_block(existing: str, document_id: str, content: str) -> str:
    start = block_start(document_id)
    end = block_end(document_id)
    block = protected_block(document_id, content)
    if start not in existing or end not in existing:
        separator = "\n\n" if existing.rstrip() else ""
        return existing.rstrip() + separator + block
    before, rest = existing.split(start, 1)
    _, after = rest.split(end, 1)
    return before.rstrip() + "\n\n" + block + after.lstrip()


def current_protected_block(existing: str, document_id: str) -> str | None:
    start = block_start(document_id)
    end = block_end(document_id)
    if start not in existing or end not in existing:
        return None
    before_end = existing.split(start, 1)[1]
    body, _ = before_end.split(end, 1)
    return f"{start}{body}{end}\n"


def _render_section(section: Spec, registry: SpecRegistry) -> list[str]:
    heading = section.data.get("heading")
    heading_text = (
        heading if isinstance(heading, str) and heading else section.display_name
    )
    heading_level = _integer_value(section.data.get("heading_level"), default=2)
    lines = [f"{'#' * heading_level} {heading_text}"]

    intro = section.data.get("intro")
    if isinstance(intro, str) and intro:
        lines.extend(["", intro])

    source_specs = [
        source
        for source_id in _string_list(section.data.get("source_refs"))
        if (source := registry.get(source_id)) is not None
    ]
    renderer = section.data.get("renderer")
    if renderer == "asset_figure":
        lines.extend(["", *_render_asset_figures(section, registry)])
    elif renderer == "bullet_list":
        lines.extend(["", *_render_bullet_list(section)])
    elif renderer == "command_table":
        lines.extend(["", *_render_command_table(section)])
    elif renderer == "doc_link_list":
        lines.extend(["", *_render_doc_link_list(section)])
    elif renderer == "json_example":
        lines.extend(["", *_render_json_example(section)])
    elif renderer == "ordered_steps":
        lines.extend(["", *_render_ordered_steps(section)])
    elif renderer == "project_layout":
        lines.extend(["", *_render_project_layout(section)])
    elif renderer == "adoption_ladder":
        lines.extend(["", *_render_adoption_ladder(section)])
    elif renderer == "source_list":
        lines.extend(["", *_render_source_list(source_specs, registry)])
    else:
        lines.extend(["", *_render_source_summary(source_specs, registry)])

    outro = section.data.get("outro")
    if isinstance(outro, str) and outro:
        lines.extend(["", outro])
    return lines


def _render_asset_figures(section: Spec, registry: SpecRegistry) -> list[str]:
    figures: list[str] = []
    for asset_id in _string_list(section.data.get("asset_refs")):
        asset = registry.get(asset_id)
        if asset is None or asset.kind != "asset":
            continue
        path = asset.data.get("path")
        alt = asset.data.get("alt")
        width = asset.data.get("width")
        if not isinstance(path, str) or not isinstance(alt, str):
            continue
        width_attr = f' width="{width}"' if isinstance(width, str) and width else ""
        figures.append(f'<img src="{path}" alt="{alt}"{width_attr}>')
    return figures or ["No governed assets are currently attached to this section."]


def _render_bullet_list(section: Spec) -> list[str]:
    return [f"- {item}" for item in _string_list(section.data.get("items"))]


def _render_command_table(section: Spec) -> list[str]:
    rows = section.data.get("commands")
    if not isinstance(rows, list):
        return ["No commands are currently declared for this section."]
    lines = ["| Command | What it does |", "|---|---|"]
    for row in rows:
        if not isinstance(row, dict):
            continue
        command = row.get("command")
        description = row.get("description")
        if isinstance(command, str) and isinstance(description, str):
            lines.append(f"| `{command}` | {description} |")
    return lines


def _render_doc_link_list(section: Spec) -> list[str]:
    links = section.data.get("links")
    if not isinstance(links, list):
        return ["No links are currently declared for this section."]
    lines: list[str] = []
    for link in links:
        if not isinstance(link, dict):
            continue
        label = link.get("label")
        href = link.get("href")
        if isinstance(label, str) and isinstance(href, str):
            lines.append(f"- [{label}]({href})")
    return lines


def _render_json_example(section: Spec) -> list[str]:
    example = section.data.get("example")
    if not isinstance(example, str) or not example:
        return ["No example is currently declared for this section."]
    return ["```json", example.rstrip(), "```"]


def _render_ordered_steps(section: Spec) -> list[str]:
    steps = _string_list(section.data.get("steps"))
    return [f"{index}. {step}" for index, step in enumerate(steps, start=1)]


def _render_project_layout(section: Spec) -> list[str]:
    layout = section.data.get("layout")
    if not isinstance(layout, str) or not layout:
        return ["No project layout is currently declared for this section."]
    return ["```text", layout.rstrip(), "```"]


def _render_adoption_ladder(section: Spec) -> list[str]:
    levels = section.data.get("levels")
    if not isinstance(levels, list):
        return ["No adoption levels are currently declared for this section."]
    lines: list[str] = []
    for level in levels:
        if not isinstance(level, dict):
            continue
        title = level.get("title")
        description = level.get("description")
        good_for = level.get("good_for")
        if not isinstance(title, str) or not isinstance(description, str):
            continue
        lines.extend([f"### {title}", "", description])
        if isinstance(good_for, str) and good_for:
            lines.extend(["", f"Good for {good_for}."])
        lines.append("")
    return lines


def _render_source_summary(specs: list[Spec], registry: SpecRegistry) -> list[str]:
    lines: list[str] = []
    for spec in specs:
        summary = rich_text_plain(spec.statement or spec.description, registry)
        if not summary:
            continue
        lines.extend([f"- `{spec.id}`: {summary}"])
    return lines or ["No source specs are currently attached to this section."]


def _render_source_list(specs: list[Spec], registry: SpecRegistry) -> list[str]:
    lines: list[str] = []
    for spec in specs:
        description = rich_text_plain(spec.description, registry)
        suffix = f" - {description}" if description else ""
        lines.append(f"- `{spec.id}` ({spec.kind}): {spec.display_name}{suffix}")
    return lines or ["No source specs are currently attached to this section."]


def _string_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, str) and item]


def _integer_value(value: object, *, default: int = 0) -> int:
    return value if isinstance(value, int) else default
