from __future__ import annotations

GENERATED_HEADER = "<!-- generated by grounded; do not edit by hand -->"
CSS_FILENAME = "style.css"
INDEX_FILENAME = "index.html"
LINK_COMPONENT_FILENAME = "grounded-link.js"
SEARCH_FILENAME = "search-index.json"
