from __future__ import annotations

import json
from collections import Counter
from html import escape
from pathlib import Path
from typing import Any

from jinja2 import ChoiceLoader, DictLoader, Environment, FileSystemLoader, select_autoescape

from .models import LatticeConfig, Spec
from .registry import SpecRegistry


GENERATED_HEADER = "<!-- generated by lattice; do not edit by hand -->"
CSS_FILENAME = "style.css"
LINK_COMPONENT_FILENAME = "lattice-link.js"
SEARCH_FILENAME = "search-index.json"


def render_all(config: LatticeConfig, registry: SpecRegistry, *, check: bool = False) -> list[str]:
    site = build_site(config, registry)
    stale: list[str] = []
    for path, content in site.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(config.root)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if not check:
        prune_obsolete_outputs(config, set(site))
    return stale


def prune_obsolete_outputs(config: LatticeConfig, expected: set[Path]) -> None:
    units_dir = config.generated_docs_dir / "units"
    if not units_dir.exists():
        return
    for path in units_dir.glob("*.html"):
        if path not in expected:
            path.unlink()


def build_site(config: LatticeConfig, registry: SpecRegistry) -> dict[Path, str]:
    index_path = config.generated_docs_dir / "project-memory.html"
    graph = lattice_registry_for(config, registry, index_path)
    search_index = build_search_index(config, registry, graph)
    env = template_environment(config)
    context = base_context(config, registry, graph, index_path)
    outputs = {
        config.generated_docs_dir / "project-memory.md": render_markdown(registry),
        config.generated_docs_dir / "project-memory.html": env.get_template("index.html.j2").render(
            **context,
            search_index_path=SEARCH_FILENAME,
        ),
        config.generated_docs_dir / CSS_FILENAME: render_css(config),
        config.generated_docs_dir / LINK_COMPONENT_FILENAME: render_link_component(),
        config.search_index_path: json.dumps(search_index, indent=2, sort_keys=True) + "\n",
        config.generated_llm_dir / "context-pack.md": render_llm_pack(registry),
    }
    for spec in registry.active_specs:
        output_path = unit_output_path(config, spec)
        unit_graph = lattice_registry_for(config, registry, output_path)
        unit_context = base_context(config, registry, unit_graph, output_path)
        type_def = registry.type_definition_for(spec)
        template_name = type_def.renderer if type_def else "unit.html.j2"
        if template_name not in env.list_templates():
            template_name = "unit.html.j2"
        outputs[output_path] = env.get_template(template_name).render(
            **unit_context,
            spec=spec,
            data=spec.data,
            backlinks=unit_graph[lattice_key(spec)].get("backlinks", []),
            outgoing=outgoing_links_for(spec, registry, unit_graph),
        )
    return outputs


def template_environment(config: LatticeConfig) -> Environment:
    loaders = []
    if config.templates_dir.exists():
        loaders.append(FileSystemLoader(str(config.templates_dir)))
    loaders.append(DictLoader(DEFAULT_TEMPLATES))
    env = Environment(loader=ChoiceLoader(loaders), autoescape=select_autoescape(("html", "j2")))
    env.filters["field_label"] = field_label
    env.filters["as_json"] = lambda value: json.dumps(value, indent=2, sort_keys=True)
    return env


def base_context(config: LatticeConfig, registry: SpecRegistry, graph: dict[str, dict[str, Any]], output_path: Path) -> dict[str, Any]:
    return {
        "generated_header": GENERATED_HEADER,
        "registry": registry,
        "specs": sorted(registry.active_specs, key=lambda item: (item.kind, item.id)),
        "by_type": specs_by_type(registry.active_specs),
        "type_counts": Counter(spec.kind for spec in registry.active_specs),
        "lattice_registry": graph,
        "lattice_registry_json": json.dumps(graph, sort_keys=True),
        "css_href": href_for(output_path, config.generated_docs_dir / CSS_FILENAME),
        "link_component_href": href_for(output_path, config.generated_docs_dir / LINK_COMPONENT_FILENAME),
        "unit_href": lambda spec: href_for(output_path, unit_output_path(config, spec)),
        "lattice_link": lattice_link,
    }


def specs_by_type(specs: list[Spec]) -> dict[str, list[Spec]]:
    by_type: dict[str, list[Spec]] = {}
    for spec in specs:
        by_type.setdefault(spec.kind, []).append(spec)
    return {key: sorted(value, key=lambda spec: spec.id) for key, value in sorted(by_type.items())}


def lattice_key(spec: Spec) -> str:
    return f"{spec.kind}:{spec.id}"


def unit_output_path(config: LatticeConfig, spec: Spec) -> Path:
    return config.generated_docs_dir / "units" / f"{slugify(spec.id)}.html"


def lattice_registry_for(config: LatticeConfig, registry: SpecRegistry, from_path: Path) -> dict[str, dict[str, Any]]:
    outgoing: dict[str, list[str]] = {}
    backlinks: dict[str, list[str]] = {}
    for spec in registry.active_specs:
        source = lattice_key(spec)
        targets = [target for target in spec.references if target in registry.by_id]
        outgoing[source] = [lattice_key(registry.by_id[target]) for target in targets]
        for target in targets:
            backlinks.setdefault(lattice_key(registry.by_id[target]), []).append(source)

    graph: dict[str, dict[str, Any]] = {}
    for spec in registry.active_specs:
        key = lattice_key(spec)
        graph[key] = {
            "type": spec.kind,
            "id": spec.id,
            "label": spec.data.get("name", spec.id),
            "href": href_for(from_path, unit_output_path(config, spec)),
            "summary": spec.statement,
            "outgoing": outgoing.get(key, []),
            "backlinks": [
                {
                    "type": registry.by_id[source_id].kind,
                    "id": registry.by_id[source_id].id,
                    "label": registry.by_id[source_id].data.get("name", registry.by_id[source_id].id),
                    "href": href_for(from_path, unit_output_path(config, registry.by_id[source_id])),
                }
                for source_key in sorted(backlinks.get(key, []))
                for source_id in [source_key.split(":", 1)[1]]
                if source_id in registry.by_id
            ],
        }
    return graph


def outgoing_links_for(spec: Spec, registry: SpecRegistry, graph: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    links = []
    for target_id in spec.references:
        target = registry.by_id.get(target_id)
        if target is None:
            continue
        node = graph.get(lattice_key(target))
        if node is not None:
            links.append(node)
    return links


def build_search_index(config: LatticeConfig, registry: SpecRegistry, graph: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    index: list[dict[str, Any]] = []
    for spec in sorted(registry.active_specs, key=lambda item: (item.kind, item.id)):
        type_def = registry.type_definition_for(spec)
        fields = type_def.search_fields if type_def else ("id", "name", "summary")
        text_parts = [spec.id, spec.kind]
        for field in fields:
            text_parts.extend(flatten_search_value(spec.data.get(field)))
        node = graph[lattice_key(spec)]
        text_parts.extend(str(backlink["label"]) for backlink in node.get("backlinks", []))
        index.append(
            {
                "id": spec.id,
                "type": spec.kind,
                "name": spec.data.get("name", spec.id),
                "summary": spec.statement,
                "href": node["href"],
                "text": " ".join(part for part in text_parts if part).lower(),
                "backlinks": len(node.get("backlinks", [])),
            }
        )
    return index


def flatten_search_value(value: object) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, int | float | bool):
        return [str(value)]
    if isinstance(value, list):
        result: list[str] = []
        for item in value:
            result.extend(flatten_search_value(item))
        return result
    if isinstance(value, dict):
        result = []
        for item in value.values():
            result.extend(flatten_search_value(item))
        return result
    return []


def render_css(config: LatticeConfig) -> str:
    source = config.styles_dir / CSS_FILENAME
    if source.exists():
        return source.read_text(encoding="utf-8")
    return default_css()


def render_markdown(registry: SpecRegistry) -> str:
    lines = [
        GENERATED_HEADER,
        "---",
        "last_updated: 2026-05-24",
        "---",
        "",
        "# Project Memory",
        "",
        "This file is generated from Lattice canonical knowledge units.",
        "",
    ]
    for type_name, specs in specs_by_type(registry.active_specs).items():
        lines.extend([f"## {type_name.replace('_', ' ').title()}", ""])
        for spec in specs:
            lines.extend(_render_spec_summary(spec))
    return "\n".join(lines).rstrip() + "\n"


def render_llm_pack(registry: SpecRegistry) -> str:
    lines = [
        GENERATED_HEADER,
        "---",
        "last_updated: 2026-05-24",
        "---",
        "",
        "# Lattice LLM Context Pack",
        "",
        "Use these canonical knowledge units as the source of truth. Do not duplicate or invent competing facts.",
        "",
    ]
    for spec in sorted(registry.active_specs, key=lambda item: (item.kind, item.id)):
        lines.append(f"- `{spec.id}` ({spec.kind}, owner: {spec.owner or 'unknown'}): {spec.statement}")
        refs = ", ".join(spec.references)
        if refs:
            lines.append(f"  Links: {refs}")
    return "\n".join(lines).rstrip() + "\n"


def _render_spec_summary(spec: Spec) -> list[str]:
    lines = [f"### {spec.data.get('name', spec.id)}", "", f"- ID: `{spec.id}`", f"- Type: `{spec.kind}`"]
    if spec.owner:
        lines.append(f"- Owner: `{spec.owner}`")
    if spec.statement:
        lines.extend(["", spec.statement])
    refs = ", ".join(f"`{ref}`" for ref in spec.references)
    if refs:
        lines.extend(["", f"Links: {refs}"])
    lines.append("")
    return lines


def render_link_component() -> str:
    return """\
const registryElement = document.getElementById('lattice-registry');
const latticeRegistry = registryElement ? JSON.parse(registryElement.textContent || '{}') : {};
window.latticeRegistry = latticeRegistry;

const sheet = new CSSStyleSheet();
sheet.replaceSync(`
  :host { display: inline-flex; max-width: 100%; vertical-align: baseline; }
  a { align-items: center; background: var(--color-chip-bg); border: 1px solid var(--color-chip-border); border-radius: var(--radius-sm); color: var(--color-accent-strong); display: inline-flex; font: 650 var(--font-size-sm)/1.2 var(--font-mono); max-width: 100%; padding: var(--space-2xs) var(--space-sm); text-decoration: none; }
  a:hover, a:focus { background: var(--color-accent-soft); color: var(--color-accent-strong); }
  a:focus-visible { outline: 2px solid var(--color-accent); outline-offset: 2px; }
  :host([variant="text"]) a { background: transparent; border: 0; border-radius: 0; color: var(--color-link); display: inline; font: inherit; padding: 0; }
`);

class LatticeLink extends HTMLElement {
  static observedAttributes = ['type', 'lattice-id'];
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.shadowRoot.adoptedStyleSheets = [sheet];
  }
  attributeChangedCallback() { this.render(); }
  connectedCallback() { this.render(); }
  render() {
    const type = this.getAttribute('type');
    const id = this.getAttribute('lattice-id');
    if (!type || !id) return;
    const target = latticeRegistry[`${type}:${id}`] || Object.values(latticeRegistry).find((node) => node.id === id);
    const label = (this.textContent || '').trim() || (target ? target.label : id);
    const anchor = document.createElement('a');
    anchor.href = target ? target.href : '#';
    anchor.part = 'anchor';
    anchor.dataset.latticeType = type;
    anchor.dataset.latticeId = id;
    anchor.textContent = label;
    this.shadowRoot.replaceChildren(anchor);
  }
}
if (!customElements.get('lattice-link')) customElements.define('lattice-link', LatticeLink);
"""


def lattice_link(type_name: object, unit_id: object, label: object | None = None, variant: str | None = None) -> str:
    variant_attr = f' variant="{escape(variant)}"' if variant else ""
    text = str(label) if label is not None else str(unit_id)
    return (
        f'<lattice-link type="{escape(str(type_name))}" lattice-id="{escape(str(unit_id))}"{variant_attr}>'
        f"{escape(text)}</lattice-link>"
    )


def href_for(from_path: Path, to_path: Path) -> str:
    return to_path.relative_to(from_path.parent).as_posix() if to_path.parent == from_path.parent else _relative_path(from_path.parent, to_path)


def _relative_path(from_dir: Path, to_path: Path) -> str:
    import os

    return os.path.relpath(to_path, from_dir).replace("\\", "/")


def slugify(value: object) -> str:
    text = str(value).lower()
    safe = []
    for char in text:
        safe.append(char if char.isalnum() else "-")
    return "-".join(part for part in "".join(safe).split("-") if part)


def field_label(value: str) -> str:
    return value.replace("_", " ").title()


def default_css() -> str:
    return """/* generated by lattice; central visual source of truth */
:root {
  --color-ink: #172026;
  --color-muted: #5d6872;
  --color-page: #f7f8f5;
  --color-panel: #ffffff;
  --color-soft: #eef2ed;
  --color-line: #d8ded6;
  --color-accent: #0f766e;
  --color-accent-strong: #115e59;
  --color-accent-soft: #d9f2ed;
  --color-chip-bg: #f2f6f4;
  --color-chip-border: #cdd8d4;
  --color-link: #0f5f59;
  --font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  --font-size-sm: 0.86rem;
  --space-2xs: 0.18rem;
  --space-xs: 0.35rem;
  --space-sm: 0.6rem;
  --space-md: 1rem;
  --space-lg: 1.5rem;
  --space-xl: 2.25rem;
  --radius-sm: 0.35rem;
  --radius-md: 0.5rem;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
* { box-sizing: border-box; }
body { margin: 0; color: var(--color-ink); background: var(--color-page); line-height: 1.55; }
a { color: var(--color-link); }
code { font-family: var(--font-mono); background: var(--color-soft); border-radius: var(--radius-sm); padding: 0.08rem 0.28rem; }
.page { max-width: 76rem; margin: 0 auto; padding: var(--space-xl) var(--space-lg); }
.hero { display: grid; gap: var(--space-md); margin-bottom: var(--space-xl); }
.eyebrow { color: var(--color-accent-strong); font-size: 0.78rem; font-weight: 800; letter-spacing: 0.08em; text-transform: uppercase; }
h1 { margin: 0; font-size: clamp(2.2rem, 6vw, 4.8rem); line-height: 0.96; letter-spacing: 0; }
h2 { margin-top: 0; }
.dek { max-width: 52rem; margin: 0; color: var(--color-muted); font-size: 1.1rem; }
.search { display: grid; gap: var(--space-sm); max-width: 44rem; margin-top: var(--space-lg); }
.search input { width: 100%; border: 1px solid var(--color-line); border-radius: var(--radius-md); font: inherit; padding: var(--space-sm) var(--space-md); }
.search-results { display: grid; gap: var(--space-xs); padding: 0; margin: 0; list-style: none; }
.search-results a, .card { background: var(--color-panel); border: 1px solid var(--color-line); border-radius: var(--radius-md); }
.search-results a { display: grid; padding: var(--space-sm) var(--space-md); text-decoration: none; }
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(20rem, 1fr)); gap: var(--space-md); align-items: start; }
.card { padding: var(--space-lg); }
.card h3 { margin: 0 0 var(--space-xs); }
.meta { display: flex; flex-wrap: wrap; gap: var(--space-xs); margin-top: var(--space-md); }
.pill { display: inline-flex; align-items: center; min-height: 1.65rem; border: 1px solid var(--color-chip-border); border-radius: var(--radius-sm); color: var(--color-muted); font: 650 var(--font-size-sm)/1.1 var(--font-mono); padding: 0 var(--space-sm); }
.unit-layout { display: grid; grid-template-columns: minmax(0, 2fr) minmax(18rem, 0.8fr); gap: var(--space-lg); align-items: start; }
.unit-body { white-space: pre-wrap; }
.link-list { display: flex; flex-wrap: wrap; gap: var(--space-xs); padding: 0; margin: var(--space-sm) 0 0; list-style: none; }
.raw-data { overflow: auto; max-height: 32rem; }
@media (max-width: 800px) { .page { padding: var(--space-lg) var(--space-md); } .unit-layout { grid-template-columns: 1fr; } }
"""


DEFAULT_TEMPLATES: dict[str, str] = {
    "shell.html.j2": """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{% block title %}Lattice Project Memory{% endblock %}</title>
  <link rel="stylesheet" href="{{ css_href }}" />
  <script defer src="{{ link_component_href }}"></script>
</head>
<body>
  <script type="application/json" id="lattice-registry">{{ lattice_registry_json | safe }}</script>
  <main class="page">
    {% block content %}{% endblock %}
  </main>
</body>
</html>
""",
    "index.html.j2": """{% extends "shell.html.j2" %}
{% block content %}
<header class="hero">
  <div class="eyebrow">Lattice project memory</div>
  <h1>Typed knowledge units, linked.</h1>
  <p class="dek">Generated from schema-validated Lattice units. Search, backlinks, and links are derived from the same registry.</p>
  <div class="search" data-search-root>
    <input type="search" placeholder="Search knowledge units" aria-label="Search knowledge units" data-search-input>
    <ul class="search-results" data-search-results></ul>
  </div>
</header>
{% for type_name, units in by_type.items() %}
<section class="card" aria-labelledby="{{ type_name }}-title">
  <h2 id="{{ type_name }}-title">{{ type_name | field_label }}</h2>
  <div class="grid">
  {% for spec in units %}
    <article>
      <h3><a href="{{ unit_href(spec) }}">{{ spec.data.name }}</a></h3>
      <p>{{ spec.statement }}</p>
      <div class="meta"><span class="pill">{{ spec.id }}</span><span class="pill">{{ spec.kind }}</span></div>
    </article>
  {% endfor %}
  </div>
</section>
{% endfor %}
<script>
fetch('{{ search_index_path }}')
  .then((response) => response.json())
  .then((items) => {
    const input = document.querySelector('[data-search-input]');
    const results = document.querySelector('[data-search-results]');
    const render = () => {
      const query = input.value.trim().toLowerCase();
      results.replaceChildren();
      if (!query) return;
      items.filter((item) => item.text.includes(query)).slice(0, 12).forEach((item) => {
        const li = document.createElement('li');
        const a = document.createElement('a');
        a.href = item.href;
        a.innerHTML = `<strong>${item.name}</strong><span>${item.type} · ${item.id}</span>`;
        li.append(a);
        results.append(li);
      });
    };
    input.addEventListener('input', render);
  });
</script>
{% endblock %}
""",
    "unit.html.j2": """{% extends "shell.html.j2" %}
{% block title %}{{ data.name }} · Lattice{% endblock %}
{% block content %}
<header class="hero">
  <div class="eyebrow">{{ spec.kind | field_label }}</div>
  <h1>{{ data.name }}</h1>
  <p class="dek">{{ spec.statement }}</p>
  <div class="meta"><span class="pill">{{ spec.id }}</span><span class="pill">owner: {{ spec.owner }}</span><span class="pill">status: {{ spec.status }}</span></div>
</header>
<div class="unit-layout">
  <article class="card">
    <h2>Details</h2>
    {% for key, value in data.items() %}
      {% if key not in ["id", "type", "kind", "name", "owner", "status", "references", "tests", "examples", "links"] %}
      <h3>{{ key | field_label }}</h3>
      <div class="unit-body">{{ value }}</div>
      {% endif %}
    {% endfor %}
    <h2>Raw Unit</h2>
    <pre class="raw-data"><code>{{ data | as_json }}</code></pre>
  </article>
  <aside class="card">
    <h2>Links</h2>
    <h3>Outgoing</h3>
    <ul class="link-list">
      {% for node in outgoing %}<li>{{ lattice_link(node.type, node.id, node.label) | safe }}</li>{% else %}<li class="pill">None</li>{% endfor %}
    </ul>
    <h3>Backlinks</h3>
    <ul class="link-list">
      {% for node in backlinks %}<li>{{ lattice_link(node.type, node.id, node.label) | safe }}</li>{% else %}<li class="pill">None</li>{% endfor %}
    </ul>
  </aside>
</div>
{% endblock %}
""",
    "domain_object.html.j2": """{% extends "unit.html.j2" %}""",
    "schema_gap.html.j2": """{% extends "unit.html.j2" %}""",
    "verification.html.j2": """{% extends "unit.html.j2" %}""",
}
