from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL_PATH = ROOT / "skills" / "audit-grounded-knowledge-graph" / "SKILL.md"

REQUIRED_HEADINGS = [
    "Purpose",
    "Core Principle",
    "Grounded Public Vocabulary",
    "Audit Inputs",
    "Audit Passes",
    "Output Format",
    "Script Writing Guidance",
    "Quality Bar",
    "Final Question",
]
OUTPUT_FORMAT_HEADINGS = [
    "1. Executive Summary",
    "2. Trust Summary",
    "3. Main Findings",
    "4. Refactoring Suggestions",
    "5. Verification Gaps",
    "6. Suggested Scripts",
    "7. Suggested Graph Views",
    "8. Migration Plan",
]
TRUST_STATUSES = ["verified", "checkable", "observed", "aspirational", "unknown"]
EDGE_TYPES = [
    "mentions",
    "depends_on",
    "implements",
    "verified_by",
    "tests",
    "documents",
    "derives_from",
    "illustrated_by",
    "contains",
]
FINAL_QUESTION = (
    "What trust status can this graph honestly support, and what evidence would raise it?"
)
GENERATED_WARNING = (
    "This skill is generated by Grounded. Edit the source skill file/specs, "
    "not this rendered output."
)
LEGACY_TERM = "".join(["Lat", "tice"])
# Keep the legacy token split so repository-wide public-name scans do not flag this verifier.


def main() -> int:
    argv = sys.argv[1:]
    path = SKILL_PATH
    if argv:
        if len(argv) != 2 or argv[0] != "--path":
            print("usage: verify_audit_skill_format.py [--path PATH]")
            return 1
        path = Path(argv[1])

    failures: list[str] = []
    if not path.exists():
        print(f"missing rendered skill: {path}")
        return 1

    text = path.read_text(encoding="utf-8")
    _check_generated_warning(text, failures)
    _check_required_headings(text, failures)
    _check_output_format_headings(text, failures)
    _check_vocabulary("trust status", TRUST_STATUSES, text, failures)
    _check_vocabulary("edge", EDGE_TYPES, text, failures)
    _check_final_question(text, failures)
    _check_legacy_terms(text, failures)

    if failures:
        for failure in failures:
            print(f"audit skill format failure: {failure}")
        return 1
    print("audit skill format verified")
    return 0


def _check_generated_warning(text: str, failures: list[str]) -> None:
    if GENERATED_WARNING not in text:
        failures.append("missing generated-file warning")


def _check_required_headings(text: str, failures: list[str]) -> None:
    headings = re.findall(r"^## (.+)$", text, flags=re.MULTILINE)
    if headings != REQUIRED_HEADINGS:
        failures.append(
            "required ## headings are not in fixed order: "
            f"expected {REQUIRED_HEADINGS}, found {headings}"
        )


def _check_output_format_headings(text: str, failures: list[str]) -> None:
    output_match = re.search(
        r"^## Output Format$(?P<body>.*?)(?=^## Script Writing Guidance$)",
        text,
        flags=re.MULTILINE | re.DOTALL,
    )
    if output_match is None:
        failures.append("missing Output Format section body")
        return
    headings = re.findall(r"^### (.+)$", output_match.group("body"), flags=re.MULTILINE)
    if headings != OUTPUT_FORMAT_HEADINGS:
        failures.append(
            "Output Format ### headings are not in fixed order: "
            f"expected {OUTPUT_FORMAT_HEADINGS}, found {headings}"
        )


def _check_vocabulary(
    label: str, values: list[str], text: str, failures: list[str]
) -> None:
    missing = [value for value in values if not re.search(rf"\b{value}\b", text)]
    if missing:
        failures.append(f"missing {label} vocabulary: {', '.join(missing)}")


def _check_final_question(text: str, failures: list[str]) -> None:
    if FINAL_QUESTION not in text:
        failures.append("missing final trust question")
        return
    if text.rstrip().splitlines()[-1] != FINAL_QUESTION:
        failures.append("rendered skill must end with the final trust question")


def _check_legacy_terms(text: str, failures: list[str]) -> None:
    lines = text.splitlines()
    migration_line = next(
        (index for index, line in enumerate(lines, start=1) if line == "### 8. Migration Plan"),
        None,
    )
    if migration_line is None:
        return
    migration_end = next(
        (
            index
            for index, line in enumerate(lines, start=1)
            if index > migration_line and line.startswith("## ")
        ),
        len(lines) + 1,
    )
    legacy_pattern = re.compile(rf"\b{re.escape(LEGACY_TERM)}\b", flags=re.IGNORECASE)
    disallowed = [
        str(line_number)
        for line_number, line in enumerate(lines, start=1)
        if not (migration_line <= line_number < migration_end)
        and legacy_pattern.search(line)
    ]
    if disallowed:
        failures.append(
            "legacy project-name vocabulary appears outside the migration section "
            f"on line(s): {', '.join(disallowed)}"
        )


if __name__ == "__main__":
    raise SystemExit(main())
